# -*- coding: utf-8 -*-
{
    'name': 'Kenocia Fiscal Honduras v18',
    'summary': 'Tropicalización fiscal completa de Odoo para Honduras (SAR)',
    'description': """
        Módulo fiscal para Honduras — Kenocia / Odoo 18
        =================================================

        Implementa los requerimientos del SAR (Servicio de Administración de Rentas):

        * Secuencias SAR con CAI, rangos y fechas límite de emisión
        * ISV 15% / 18%, exento y exonerado
        * Validación de RTN Honduras (14 dígitos empresa, 13 persona natural)
        * Reportes fiscales PDF (Factura, NC, ND, Boleta, Retención, Guía)
        * Reportes Excel (Ventas, DMC, SAR, Retenciones, Exoneraciones)
        * Libros SAR persistentes (Ventas, Compras/DMC, Retenciones, Exoneraciones)
        * Alertas y auditoría de secuencias y libros fiscales
        * Guías de remisión con numeración SAR
    """,
    'author': 'Kenocia (Kenosis Company)',
    'website': 'https://kenocia.com/',
    'license': 'LGPL-3',
    'category': 'Accounting/Localizations',
    'version': '18.0.1.4.20',
    'depends': [
        'base',
        'web',
        'mail',
        'hr',
        'account',
        'sale',
        'purchase',
        'stock_account',
        'purchase_stock',
        'stock',
        'sale_stock',
    ],
    'data': [
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'data/fiscal_data.xml',
        'views/res_partner.xml',
        'views/res_company_views.xml',
        'views/account_invoice_view.xml',
        'views/account_move.xml',
        'views/kc_fiscal_print_log_views.xml',
        'views/kc_fiscal_print_reissue_log_views.xml',
        'views/codigo_sar_views.xml',
        'views/account_tax.xml',
        'views/account_payment.xml',
        'views/ir_sequence.xml',
        'views/fiscal_journal_views.xml',
        'wizard/fiscal_dashboard.xml',
        'wizard/report_dmc_excel.xml',
        'wizard/report_invoice_details_excel.xml',
        'wizard/report_sales_excel.xml',
        'wizard/account_move_warning_wizard.xml',
        'wizard/print_reissue_wizard.xml',
        'wizard/print_reissue_cancel_wizard.xml',
        'wizard/sequence_alerts_wizard.xml',
        'wizard/preregistro_cai.xml',
        'wizard/fiscal_validation_wizard.xml',
        'views/sequence_alert.xml',
        'views/fiscal_menu_actions.xml',
        'wizard/report_sales_sar.xml',
        'wizard/report_retentions_sar.xml',
        'wizard/report_exemptions_sar.xml',
        'wizard/reset_sequence.xml',
        'wizard/resolve_alert.xml',
        'views/sequence_audit.xml',
        'views/consumidor_final_audit_views.xml',
        'views/book_sales_views.xml',
        'views/book_purchases_views.xml',
        'views/book_retentions_views.xml',
        'views/fiscal_books_views.xml',
        'wizard/generate_book_wizard.xml',
        'wizard/manual_uso.xml',
        'views/stock_lot_views.xml',
        'views/menu.xml',
        'views/product_category_views.xml',
        'views/product_template.xml',
        'views/stock_move_line.xml',
        'views/stock_picking.xml',
        'views/sale_order_views.xml',
        'report/report_invoice_sar.xml',
        'report/report_credit_note.xml',
        'report/report_debit_note.xml',
        'report/custom_layout.xml',
        'report/Paper_format.xml',
        'report/report_comprobante_retencion.xml',
        'report/report_boleta_compra.xml',
        'report/report_guia_remision.xml',
        'report/report_salida_inventario.xml',
        'report/report_journal_entry.xml',
        'report/custom_layout_sale.xml',
        'report/report_sale_quotation.xml',
        'report/report_sale_proforma.xml',
        'report/custom_layout_purchase.xml',
        'report/report_purchase_order.xml',
        'report/purchase_report_action.xml',
        'report/sale_report_action.xml',
        'report/action_report.xml',
    ],
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'application': True,
    'auto_install': False,
    'sequence': 1,
    'external_dependencies': {
        'python': ['openpyxl', 'xlsxwriter'],
    },
    'currency': 'HNL',
    'countries': ['HN'],
    'images': ['static/description/icon.png'],
    'assets': {
        'web.assets_backend': [
            'kc_fiscal_hn_v18/static/src/scss/fiscal_dashboard.scss',
            'kc_fiscal_hn_v18/static/src/scss/preregistro_cai.scss',
            'kc_fiscal_hn_v18/static/src/scss/fiscal_sequence.scss',
            'kc_fiscal_hn_v18/static/src/scss/sequence_alerts.scss',
            'kc_fiscal_hn_v18/static/src/scss/manual_uso.scss',
        ],
    },
    'support': 'support@kenocia.com',
    'maintainer': 'Kenocia (Kenosis Company)',
}
